spring:
  application:
    name: SERVICE-REGISTRY

server:
  port: 8761

eureka:
  client:
    register-with-eureka:false
    fetch-registry:false

management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

