version: "3.9"
services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  rabbitmq:
    image: 'rabbitmq:3.13.3-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=quest'
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_PASSWORD}"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  service-registry:
    build:
      context: service-registry
    ports:
      - "8761:8761"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8761/actuator/health/readiness || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
  config-server:
    build:
      context: config-server
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    depends_on:
      service-registry:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8888/actuator/health/readiness || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
  department-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: department_db
    ports:
      - "5432:5432"
    restart: unless-stopped
  department-service:
    build:
      context: department-service
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      department-db:
        condition: service_started
      service-registry:
        condition: service_started
      config-server:
        condition: service_healthy
  employee-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: employee_db
    ports:
      - "5433:5432"
    restart: unless-stopped
  employee-service:
    build:
      context: employee-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CONFIG_IMPORT : optional:configserver:http://config-server:8888
    ports:
      - "8082:8080"
    depends_on:
      employee-db:
        condition: service_started
      service-registry:
        condition: service_started
      config-server:
        condition: service_healthy

  organization-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: organization_db
    ports:
      - "5434:5432"
    restart: unless-stopped
  organization-service:
    build:
      context: organization-service
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      employee-db:
        condition: service_started
      service-registry:
        condition: service_started
      config-server:
        condition: service_healthy

  api-gateway:
    build:
      context: api-gateway
    ports:
      - "9191:9191"
    depends_on:
      service-registry:
        condition: service_healthy
      config-server:
        condition: service_healthy

  frontend:
    build:
      context: react-frontend
    ports:
      - "8080:3000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    container_name: prometheus

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/