version: "3.9"
services:
  service-registry:
    build:
      context: service-registry
    ports:
      - "8761:8761"
  department-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: department_db
    ports:
      - "5432:5432"
    restart: unless-stopped
  department-service:
    build:
      context: department-service
    ports:
      - "8080:8080"
    depends_on:
      - department-db
      - service-registry
  employee-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: employee_db
    ports:
      - "5433:5432"
    restart: unless-stopped
  employee-service:
    build:
      context: employee-service
    ports:
      - "8081:8081"
    depends_on:
      - employee-db
      - service-registry