spring:
  application:
    name: API-GATEWAY
  zipkin:
    base-url: http://zipkin:9411/
  cloud:
    gateway:
      globalcors:
        corsConfiguration:
          [/**]:
            allowedOrigins: "*"
            allowedMethods: GET, POST, PUT, DELETE
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        web: DEBUG
        cloud:
          gateway:
            handler:
              RoutePredicateHandlerMapping: DEBUG

server:
  port: 9191

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"

