spring:
  application:
    name: EMPLOYEE-SERVICE
  config:
    import: optional:configserver:http://config-server:8888
  rabbitmq:
    host: rabbitmq
    port: 15672
    username: quest
    password: quest
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: admin
#    password: admin
#    url: jdbc:postgresql://employee-db:5432/employee_db
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#server:
#  port: 8081
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#springdoc:
#  swagger-ui:
#    path : /gui-docs
#  api-docs:
#    path : /api-docs
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://service-registry:8761/eureka/