global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: eureka-discovery
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: http://service-registry:8761/eureka
        refresh_interval: 30s
    static_configs:
      - targets: [ 'service-registry:8761' ]
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']