spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          skipSslValidation: true
          uri: https://github.com/Nikstanov/ivc_practice_microservices_configs
          clone-on-start: true
server:
  port: 8888

encrypt:
  key: default_encrypt_key

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true